# 默认窗口无标题栏，16:9的窗口比例启动
window:
  #rounded_corners: 10
  # decorations: "none"
  #dimensions:
  #columns: 120
  #lines: 30
  startup_mode: Maximized
  padding: 
    x: 2
    y: 2

# 透明度
  opacity: 1
# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true


# 主题
colors:
  primary:
    foreground: '0xeeeeec'
  normal:
     black:   '0x2e3436'
     red:     '0xFF0000'
     green:   '0x00FF00'
     yellow:  '0xFF9900'
     blue:    '0x00BFFF'
     magenta: '0xFF00FF'
     cyan:    '0x00FFFF'
     white:   '0xd3d7cf'
  bright:
     black:   '0x2e3436'
     red:     '0xef2929'
     green:   '0x00FF7F'
     yellow:  '0xfce94f'
     blue:    '0x729fcf'
     magenta: '0xad7fa8'
     cyan:    '0x34e2e2'
     white:   '0xeeeeec'

font:
  size: 16
  
  normal:
    family: JetBrainsMono
    #family: Fira Code
  bold:
    family: JetBrainsMono
      #family: Fira Code
  italic:
    family: JetBrainsMono
      #family: Fira Code
  offset:
    x: 1
    y: 0
cursor:
  style: Beam
  blinking: On
